wh_db:
  image: rethinkdb
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  volumes:
    - ./data:/data

wh_api:
  image: mhart/alpine-node:9
  ports:
    - "3000:3000"
  volumes:
    - ./src:/src
  working_dir: /src
  command: npm start
  links:
    - wh_db
  environment:
    SECRET_KEY: "FOOBAR123"
    NODE_ENV: "development"

