version: "3.2"


services:
  wh_db:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "29015:29015"
    volumes:
      - data:/data

  wh_api:
    # image: mhart/alpine-node:9
    build: .
    ports:
      - "80:3000"
    # volumes:
      # - ./src:/src
    # volumes:
    #   - type: "local"
    #     source: ./src
    #     target: "/src"
    
    # working_dir: /src

    # command: sh
    links:
      - wh_db
    environment:
      SECRET_KEY: "867r5dfytugihojig7f89678uyhj"
      NODE_ENV: "production"

volumes:
  data:
    driver: local