version: "3.2"


services:
  wh_db:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "29015:29015"
    volumes:
      - .data:/data

  wh_api:
    image: mhart/alpine-node:9
    command: npm start
    ports:
      - "80:80"
    volumes:
      - ./src:/src    
    working_dir: /src

    links:
      - wh_db
    environment:
      SECRET_KEY: "867r5dfytugihojig7f89678uyhj"
      NODE_ENV: "production"
      PORT: 80